<?php
use Chayka\Auth\AuthHelper;
use Chayka\Helpers\Util;
use Chayka\Helpers\NlsHelper;

$isFbApiAvailable = AuthHelper::isFacebookApiAvailable();
$isInApiAvailable = AuthHelper::isLinkedInApiAvailable();
$areSocialsAvailable = $isFbApiAvailable || $isInApiAvailable;

?>

<div data-ng-controller="chayka-auth-login" class="form_screen screen_login ng-cloak" data-screen-title="<?php NlsHelper::__('header_login_screen');?>" data-ng-show="isOpen">
    <h2><?php NlsHelper::__('header_login_screen');?></h2>
    <form data-ng-submit="buttonLoginClicked()" data-form-validator="validator" novalidate="novalidate">
<!--        <input type="submit" style="position: absolute; left: -9999px; width: 1px; height: 1px;"/>-->
        <?php if($areSocialsAvailable):?>
            <div class="social_logins" >
                <h2><?php $this->__('header_social_login');?>:</h2>
                <ul class="buttons">
                    <?php if($isFbApiAvailable):?>
                        <li class="facebook"><a data-auth-facebook-button href="#facebook-login">Facebook</a></li>
                    <?php endif;?>
                    <?php if($isInApiAvailable):?>
                        <li class="linkedin"><a data-auth-linkedin-button href="#linkedin-login">LinkedIn</a></li>
                    <?php endif;?>
                </ul>
                <div class="or_common"><?php $this->__('or');?></div>
            </div>
        <?php endif;?>
        <div class="form_field email_login stretch" data-form-field="email" data-check-email="<?php NlsHelper::__('message_validate_email', 'member@'.Util::serverName())?>" data-check-required="<?php NlsHelper::__('message_required');?>">
            <label><?php NlsHelper::__('label_email')?></label>
            <input type="email" data-ng-model="fields.email" title="<?php NlsHelper::__('label_email')?>"/>
        </div>
        <div class="form_field password stretch" data-form-field="password" data-check-required="<?php NlsHelper::__('message_required');?>">
            <label><?php NlsHelper::__('label_password')?></label>
            <input type="password" data-ng-model="fields.password"  title="<?php NlsHelper::__('label_password')?>"/>
        </div>
        <div class="form_results">
            <div data-spinner="spinner" class="form_spinner"></div>
            <div data-form-message class="form_message"></div>
        </div>
        <div class="form_buttons">
            <button class="button_login"><?php NlsHelper::__('button_login');?></button>
        </div>
    </form>

</div>
