<?php

use Chayka\Helpers\NlsHelper;

?>

<div class="form_screen screen_ask_password ng-cloak" data-ng-controller="chayka-auth-password-ask" data-screen-title="<?php NlsHelper::__('header_ask_password_screen');?>" data-ng-show="isOpen">
    <h2><?php NlsHelper::__('header_ask_password_screen');?></h2>
    <form data-ng-submit="buttonConfirmPasswordClicked()" data-form-validator="validator">
        <div class="form_hint">
            {{message}}
        </div>
        <div class="form_field password stretch" data-form-field="password" data-check-required="<?php NlsHelper::__('message_required');?>">
            <label><?php NlsHelper::__('label_password');?>:</label>
            <input type="password" data-ng-model="fields.password" title="<?php NlsHelper::__('label_password');?>"/>
        </div>
        <div class="form_results">
            <div data-spinner="spinner" class="form_spinner"></div>
            <div data-form-message class="form_message"></div>
        </div>
        <div class="form_buttons">
            <button class="{{getButtonClass()}} button_password_confirm"><?php NlsHelper::__('button_password_confirm');?></button>
        </div>
    </form>
</div>
