<?php
	use Chayka\WP\Models\UserModel;
	use Chayka\WP\Helpers\AclHelper;
    $this->declareVars([
	    'showLabels' => true,
	    'avatarSize' => 48,
    ]);
	$user = UserModel::currentUser();
	$currentUserId = $user->getId();
	$avatar = get_avatar($user->getEmail(), $this->avatarSize);
	$avatar = str_replace('<img ', '<img data-ng-src="{{avatar('.$this->avatarSize.')}}" ', $avatar);
?>
<div class="bem-auth" data-ng-controller="auth-user-menu">
	<div class="bem-auth-user_menu" <?php $this->hidden(!$currentUserId);?> data-ng-show="isUserLoggedIn()">
		<div class="user_menu-header">
			<?php echo $avatar;?>
			<span class="user-display_name" data-ng-bind="user.display_name"><?php echo $user->getDisplayName(); ?></span>
		</div>
		<ul class="user_menu-options">
			<?php $isUserPrivileged = (AclHelper::isAdmin() || AclHelper::isEditor() || AclHelper::isAuthor());?>
			<li class="link_console" <?php $this->hidden(!$isUserPrivileged);?> data-ng-show="isUserPrivileged()"><a href="/wp-admin/">Консоль</a></li>
			<li class="link_profile"><a data-ng-href="{{user.profile_link}}" href="<?php echo $user->getProfileLink();?>">Профиль</a>
			<li class="link_change_password" <?php $this->hidden(UserModel::currentUser()->getMeta('source'));?> data-ng-hide="!isUserNative()"><a href="#change-password">Сменить пароль</a></li>
			<li class="link_logout"><a href="#logout">Выход</a></li>
		</ul>
	</div>
	<div class="bem-auth-controls"  <?php $this->hidden($currentUserId);?> data-ng-hide="isUserLoggedIn()">
		<ul>
			<li class="link_login_facebook"><a href="#facebook-login"><i></i>Войти <span class="via">через Facebook</a></li>
			<li class="link_login_linkedin"><a href="#linkedin-login"><i></i>Войти <span class="via">через LinkedIn</a></li>
			<li class="link_login"><a href="#login"><i></i>Войти</a></li>
			<li class="link_join"><a href="#join"><i></i>Регистрация</a></li>
		</ul>
	</div>

</div>
