<h2>Auth Options</h2>

<div data-ng-app="chayka-options-form">
    <div data-ng-controller="optionsForm" data-ng-init="namespace = 'Chayka.Auth'">
        <form data-form-validator="validator" novalidate="novalidate">
            <div class="form_field" data-form-field="authMode">
                <label>SMTP Auth</label><select data-ng-init="options.authMode='reload'; authOptions = {'reload': 'Page Reload', 'event': 'Publish Event'}" data-ng-model="options.authMode" data-ng-options="key as value for (key, value) in authOptions" ></select>
            </div>
            <div class="form_field" data-form-field="urlLogin">
                <label>Login url</label><input type="text" data-ng-init="options.urlLogin=''" data-ng-model="options.urlLogin"/>
            </div>
            <div class="form_field" data-form-field="urlJoin">
                <label>Join url</label><input type="text" data-ng-init="options.urlJoin=''" data-ng-model="options.urlJoin"/>
            </div>
            <div class="form_field" data-form-field="urlForgotPassword">
                <label>Forgot password url</label><input type="text" data-ng-init="options.urlForgotPassword=''" data-ng-model="options.urlForgotPassword"/>
            </div>
            <div class="form_field" data-form-field="urlLoggedIn">
                <label>Logged in url</label><input type="text" data-ng-init="options.urlLoggedIn=''" data-ng-model="options.urlLoggedIn"/>
            </div>
            <div class="form_field" data-form-field="urlLoggedOut">
                <label>Logged out url</label><input type="text" data-ng-init="options.urlLoggedOut=''" data-ng-model="options.urlLoggedOut"/>
            </div>
            <button data-ng-click="saveOptions();">Save</button>
        </form>
    </div>
</div>