<?php

use Chayka\Helpers\Util;
use Chayka\WP\Helpers\NlsHelper;

?>
<div class="form_screen screen_join" data-ng-controller="join" data-screen-title="<?php NlsHelper::__('header_join_screen')?>">
    <h2><?php NlsHelper::__('header_join_screen')?></h2>
    <form data-ng-submit="buttonJoinClicked()" data-form-validator="validator">
<!--        <input type="submit" style="position: absolute; left: -9999px; width: 1px; height: 1px;"/>-->
        <div class="form_field email_join" data-form-field="email" data-check-email="<?php NlsHelper::__('message_validate_email', 'member@'.Util::serverName())?>" data-check-required="<?php NlsHelper::__('message_required');?>">
            <label><?php NlsHelper::__('label_email')?>:</label>
            <input type="text" data-ng-model="email" />
        </div>
        <div class="form_field name" data-form-field="name" data-check-regexp-pattern="^[A-Za-z\d\-]+$" data-check-regexp-message="<?php NlsHelper::__('message_validate_username');?>" data-check-required="<?php NlsHelper::__('message_required');?>">
            <label><?php NlsHelper::__('label_username')?>:</label>
            <input type="text" data-ng-model="name" />
        </div>
<!--        <div class="form_field password" data-form-field="password">-->
<!--            <label>Password</label>-->
<!--            <input type="password" data-ng-model="password"/>-->
<!--        </div>-->
        <div class="form_results">
            <div data-spinner="spinner"></div>
            <div class="form_message" data-ng-show="!!message">{{message}}</div>
        </div>
        <div class="form_buttons">
            <button data-ng-click="buttonJoinClicked()" class="button_join"><?php NlsHelper::__('button_join');?></button>
        </div>
    </form>
</div>