<h1>New password on <?php echo $_SERVER['SERVER_NAME'];?>!</h1>

<div>
    At <a href="http://<?php echo $_SERVER['SERVER_NAME'];?>"><?php echo $_SERVER['SERVER_NAME'];?></a>
    we have received a request to set a new password for the account <strong><?php echo $this->user->getLogin();?></strong>
</div>
<div>
    If that was unintentional request, just don't pay any attention on this email.
</div>
<div>
    To set a new password, please follow this <a href="http://<?php echo $_SERVER['SERVER_NAME'].'?activationkey='.$this->activationKey.'&login=' . rawurlencode($this->user->getLogin());?>">link</a>
</div>
