<h1>New password for <?php echo $_SERVER['SERVER_NAME'];?>!</h1>

<div>
    You have successfully set a new password at <a href="http://<?php echo $_SERVER['SERVER_NAME'];?>"><?php echo $_SERVER['SERVER_NAME'];?></a>.
</div>
<div>
    <h2>Your new credentials:</h2>
    <dl><dt>email:</dt><dd><?php echo $this->user->getEmail();?></dd></dl>
    <?php if($this->user->getEmail()!=$this->user->getLogin()):?>
    <dl><dt>name:</dt><dd><?php echo $this->user->getLogin();?></dd></dl>
    <?php endif;?>
    <dl><dt>password:</dt><dd><?php echo $this->password;?></dd></dl>
    <div class="clearfloat"></div>
</div>
