<?php
$showName = !in_array($this->user->getLogin(), array(
    $this->user->getEmail(),
    str_replace('@', '.', $this->user->getEmail())
));
?>
<h1>Добро пожаловать на <?php echo $_SERVER['SERVER_NAME'];?>!</h1>

<div>
    Поздравляем, вы зарегистрировались на сайте <a href="http://<?php echo $_SERVER['SERVER_NAME'];?>"><?php echo $_SERVER['SERVER_NAME'];?></a>.
</div>
<div>
    <h2>Ваши учетные данные:</h2>
    <dl><dt>email:</dt><dd><?php echo $this->user->getEmail();?></dd></dl>
    <?php if($showName):?>
    <dl><dt>псевдоним:</dt><dd><?php echo $this->user->getLogin();?></dd></dl>
    <?php endif;?>
    <dl><dt>пароль:</dt><dd><?php echo $this->password;?></dd></dl>
    <div class="clearfloat"></div>
</div>
<div>
    Чтобы изменить пароль перейдите по <a href="http://<?php echo $_SERVER['SERVER_NAME'].'?activationkey='.$this->activationKey . sprintf('%x', $this->user->getId());?>">ссылке</a>
</div>
