<?php
$showName = !in_array($this->user->getLogin(), array(
    $this->user->getEmail(),
    str_replace('@', '.', $this->user->getEmail())
));
?>
<h1>Welcome to <?php echo $_SERVER['SERVER_NAME'];?>!</h1>

<div>
    Congrats! You have joined <a href="http://<?php echo $_SERVER['SERVER_NAME'];?>"><?php echo $_SERVER['SERVER_NAME'];?></a>.
</div>
<div>
    <h2>Your credentials:</h2>
    <dl><dt>email:</dt><dd><?php echo $this->user->getEmail();?></dd></dl>
    <?php if($showName):?>
    <dl><dt>name:</dt><dd><?php echo $this->user->getLogin();?></dd></dl>
    <?php endif;?>
    <dl><dt>password:</dt><dd><?php echo $this->password;?></dd></dl>
    <div class="clearfloat"></div>
</div>
<div>
    To set a new password, please follow this <a href="http://<?php echo $_SERVER['SERVER_NAME'].'?activationkey='.$this->activationKey. sprintf('%x', $this->user->getId());?>">link</a>
</div>

